# Generated by Django 6.0.5 on 2026-05-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='идентификатор кампании')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='название кампании')),
                ('image', models.CharField(blank=True, max_length=128, verbose_name='иллюстрация')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='идентификатор группы')),
                ('title', models.CharField(max_length=256, verbose_name='название группы')),
                ('image', models.CharField(blank=True, max_length=128, verbose_name='иллюстрация')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='universal_app.campaign', verbose_name='кампания')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='universal_app.group', verbose_name='родительская группа')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='идентификатор элемента')),
                ('title', models.CharField(max_length=256, verbose_name='название элемента')),
                ('description', models.TextField(blank=True, verbose_name='описание элемента')),
                ('code_name', models.CharField(max_length=6, verbose_name='кодовое название элемента')),
                ('image', models.CharField(blank=True, max_length=128, verbose_name='иллюстрация')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='universal_app.group', verbose_name='группа')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_as_a', to='universal_app.element', verbose_name='элемент A')),
                ('element_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_as_b', to='universal_app.element', verbose_name='элемент B')),
                ('results', models.ManyToManyField(related_name='produced_by', to='universal_app.element', verbose_name='результаты реакции')),
            ],
        ),
    ]
