# Generated by Django 6.0.5 on 2026-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='этот элемент появляется в начале'),
        ),
    ]
